### PR TITLE
Update the library to use Gulp, Markdown and new dependencies version

### PR DESCRIPTION
**Pull request by Tuizi**
Update the library to use Gulp, Markdown and new dependencies version

# Version
Bump to version 1.0 as the build process is a breaking changer

# Changes
- .gitignore ignore JetBrains files and OSX files
- .editorconfig to be sure all contributors are using 2 spaces indentations
- Use gulp instead of a makefile (crossplatform compatibility)
- Update readme.md file
- Use jquery as a npm dependency
- Generate a dist folder with full and minified file

# Bug fixes
Others:
- Fix semantic and malformed DOM inside demo.html
- Fix a jshint error in truncate.js

### CODE REVIEW

**Comment by Tuizi** [comment]
The goal is to be able to add new features after that.

**Comment by jeffchan** [comment]
This is awesome. Thank you!

I'm merging now.

**Comment by jeffchan** [comment]
Published on NPM. https://www.npmjs.com/package/truncate.js 

If you send me your NPM username, I can also add you as a collaborator.

**Comment by Tuizi** [comment]
Cool, thanks :+1: Yes please add me, I created my account: @tuizi also

**Pull request merged**
